exclude: ^.*\.(jpg|JPG|gif|GIF|doc|DOC|pdf|PDF|svg|SVG|png|PNG)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      - id: check-merge-conflict
      - id: end-of-file-fixer

#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: "v0.31.1"
#    hooks:
#      - id: markdownlint
#        files: \.md$
#        language_version: "13.14.0"
#        args: [--fix]

#  - repo: https://github.com/pycqa/flake8
#    rev: 4.0.1
#    hooks:
#      - id: flake8
#        args: [--max-line-length=120]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        # TODO: black ultimately without exclusions
        exclude: (^.*tests\/.*$)
        args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        # TODO: isort ultimately without exclusions
        exclude: (^.*tests\/.*$)
        args: [--settings-path=pyproject.toml, --filter-files]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.942
#    hooks:
#      - id: mypy
#        exclude: (^.*tests\/.*$|^.*setup.py)
#        args: [--config=pyproject.toml]
