[tool.black]
target-version = ['py38']
line-length = 120
force-exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
  | vendor
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_glob = '*/versions/*, */vendor/**'
default_section = "THIRDPARTY"

[tool.mypy]
python_version = 3.9
show_error_codes = true
ignore_missing_imports = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
exclude = ['^setup.py$']
